# Generated by Django 2.2.1 on 2019-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(null=True, upload_to='course'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='img',
            field=models.ImageField(null=True, upload_to='teacher'),
        ),
    ]
