# Generated by Django 2.2.1 on 2019-07-17 01:44

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
