# Generated by Django 2.2.1 on 2019-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=5),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=5),
        ),
    ]
