# Generated by Django 2.2.1 on 2019-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(upload_to='Ads'),
        ),
    ]
